### PR TITLE
Custom album for photos where i tagged

### PR DESCRIPTION
**Pull request by Elshad**

### CODE REVIEW

**Comment by floriangbh** [comment]
Hello ! Thank you ! 
I will set default image asap.
Can you make this PR on develop branch please ? :-)

**Comment by Elshad** [comment]
Of course.
I did change branch :)

**Comment by floriangbh** [comment]
Humm, did you test it ? ^^
Where is recovered the album id ?

**Comment by Elshad** [comment]
Yes i did. There is not specific album for tagged photos in Facebook. There is only `/me/photos` API for tagged photos. So i did use string `idPhotosOfYouTagged` as id for this custom album

**Comment by floriangbh** [comment]
Oh yes sorry, so maybe boolean is more appropriate in the album model :-) 
I will make some change + default picture and push it. For the album cover of "Photos of you" maybe I can set the Facebook account profile picture if I can retrieve it ?

Another problem is if there is no picture in the album... Maybe add the "photos of you" album at the end or add on/off flag can be cool 🤔

**Comment by Elshad** [comment]
Goog idea

---
For profile pic:
```
let uStr = "https://graph.facebook.com/me?fields=picture&access_token=%@"
        if let url = URL(string: String(format: uStr, FBSDKAccessToken.current().tokenString)),
            let dict = try? JSONSerialization.jsonObject(with: Data(contentsOf: url), options: .allowFragments) as? [String: AnyObject],
            let dPicture = dict?["picture"] as? [String: AnyObject],
            let dData = dPicture["data"] as? [String: AnyObject],
            let dUrl = dData["url"] as? String,
            let profilePicUrl = URL(string: dUrl) {
            //
        }
```
I now it is not good looking code, but it is work :)

---
Or we can request `/me/photos` API before show "Photos of you". If there will at least one image we show album and use this image for thumb, else not show album :)

**Pull request merged**
