### PR TITLE
Optional maximum selected pictures mode

### PR DESCRIPTION
**Pull request by pak-amsiq**
Developer now has the possibility to limit multiple selection to a maximumSelectedPictures count, when multiple selection mode is active.

### CODE REVIEW

**Comment by floriangbh** [comment]
Thank you ! 🍺

**Comment by pak-amsiq** [comment]
Thank you for quick merge. 

Could you merge the commit into master, in order to track your pod on master, instead of our forked pod?

**Comment by floriangbh** [comment]
Just merged develop into master. You can use the last commit for your pod file ! 
I will make release asap on cocoapod  :)

**Comment by pak-amsiq** [comment]
I've just wait for the release update. Ty :-)

**Comment by floriangbh** [comment]
v1.2.2 released on cocoapod !

**Comment by pak-amsiq** [comment]
Thank you :-)

**Pull request merged**
