### PR TITLE
GBHFacebookPickerConfig: Possible to insert custom namespaced localiz…

### PR DESCRIPTION
**Pull request by tof-amsiq**
…ed strings

### CODE REVIEW

**Comment by floriangbh** [comment]
Hello @tof-amsiq ,

Maybe we can create a new struct into `GBHFacebookPickerConfig` ? 
For exemple : `public struct TextConfig` to put all the text.  

Thanks

**Comment by tof-amsiq** [comment]
Yes of course, try to take a look at it now.

**Comment by tof-amsiq** [comment]
Thank you, can you please make a release ?

**Comment by floriangbh** [comment]
The develop branch have the select all new feature. I need to test it and improve some layout problem before making a release. You can use the develop branch in your pod if you need absolutely this PR :)

**Comment by tof-amsiq** [comment]
When do you think the expected date for release is ?

**Comment by floriangbh** [comment]
Idk, I don't have a lot of time at this period, currently at the WWDC :) 

You can use : pod 'GBHFacebookImagePicker', :git => 'https://github.com/floriangbh/GBHFacebookImagePicker.git', :branch => 'develop' ...

**Pull request merged**
